-- Câu 1
SELECT PRODUCTLINE, YEAR_ID, DEALSIZE, SUM(sales) AS REVENUE
FROM SALES_DATASET_RFM_PRJ
GROUP BY PRODUCTLINE, YEAR_ID, DEALSIZE
ORDER BY PRODUCTLINE
-- Câu 2
WITH cte1 AS(
SELECT year_id, month_id, sum(sales) AS REVENUE, count(ordernumber) AS ORDER_NUMBER
FROM SALES_DATASET_RFM_PRJ
GROUP BY year_id, month_id
ORDER BY year_id),
cte2 AS(
SELECT year_id, month_id, REVENUE, ORDER_NUMBER,
DENSE_RANK()OVER(PARTITION BY year_id ORDER BY REVENUE DESC) AS rnk1,
DENSE_RANK()OVER(PARTITION BY year_id ORDER BY ORDER_NUMBER DESC) AS rnk2
FROM cte1)
SELECT month_id, REVENUE, ORDER_NUMBER
FROM cte2
WHERE rnk1 = 1 AND rnk2 = 1
-- Câu 3
WITH cte1 AS(
SELECT productline, sum(sales) AS REVENUE, count(ordernumber) AS ORDER_NUMBER
FROM SALES_DATASET_RFM_PRJ
WHERE month_id = 11
GROUP BY productline),
cte2 AS(
SELECT productline, REVENUE, ORDER_NUMBER,
ROW_NUMBER()OVER(ORDER BY REVENUE DESC) AS rnk1,
ROW_NUMBER()OVER(ORDER BY ORDER_NUMBER DESC) AS rnk2
FROM cte1)
SELECT productline, REVENUE, ORDER_NUMBER
FROM cte2
WHERE rnk1=1 AND rnk2 = 1
-- Câu 4
WITH cte1 AS(
SELECT year_id, productline, sum(sales) AS REVENUE
FROM SALES_DATASET_RFM_PRJ
WHERE country = 'UK'
GROUP BY year_id, productline
ORDER BY year_id),
cte2 AS(
SELECT year_id, productline, REVENUE,
DENSE_RANK()OVER(PARTITION BY year_id ORDER BY REVENUE DESC) AS rnk1
FROM cte1)
SELECT year_id, productline, REVENUE,
RANK()OVER(ORDER BY REVENUE DESC)
FROM cte2
WHERE rnk1 = 1
-- Câu 5

