-- câu 1
ALTER TABLE SALES_DATASET_RFM_PRJ
ALTER COLUMN quantityordered TYPE numeric USING (trim(quantityordered)::numeric),
ALTER COLUMN priceeach TYPE numeric USING (trim(priceeach)::numeric),
ALTER COLUMN orderlinenumber TYPE numeric USING (trim(orderlinenumber)::numeric),
ALTER COLUMN sales TYPE numeric USING (trim(sales)::numeric),
ALTER COLUMN orderdate TYPE date USING (trim(orderdate)::date),
ALTER COLUMN msrp TYPE numeric USING (trim(msrp)::numeric)
-- câu 2: nhờ mn chữa giúp em câu này
-- câu 3
ALTER TABLE SALES_DATASET_RFM_PRJ ADD COLUMN CONTACTLASTNAME VARCHAR;
ALTER TABLE SALES_DATASET_RFM_PRJ ADD COLUMN CONTACTFIRSTNAME VARCHAR;
UPDATE SALES_DATASET_RFM_PRJ
SET CONTACTLASTNAME = INITCAP(LEFT(LEFT(contactfullname, POSITION('-' IN contactfullname)-1));
UPDATE SALES_DATASET_RFM_PRJ
SET CONTACTFIRSTNAME = INITCAP(RIGHT(contactfullname, LENGTH(contactfullname) - LENGTH(LEFT(contactfullname, POSITION('-' IN contactfullname)))));
-- câu 4
ALTER TABLE SALES_DATASET_RFM_PRJ ADD COLUMN QTR_ID INT;
ALTER TABLE SALES_DATASET_RFM_PRJ ADD COLUMN MONTH_ID INT;
ALTER TABLE SALES_DATASET_RFM_PRJ ADD COLUMN YEAR_ID INT;
UPDATE SALES_DATASET_RFM_PRJ;
SET QTR_ID = EXTRACT(QUARTER FROM ORDERDATE)
UPDATE SALES_DATASET_RFM_PRJ;
SET MONTH_ID = EXTRACT(MONTH FROM ORDERDATE)
UPDATE SALES_DATASET_RFM_PRJ;
SET YEAR_ID = EXTRACT(YEAR FROM ORDERDATE)
-- câu 5
--cách 1: boxplot
WITH twt_min_max_value AS (
SELECT Q1-1.5*IQR AS min_value, Q3+1.5*IQR AS max_value FROM (
SELECT percentile_cont(0.25) WITHIN GROUP (ORDER BY QUANTITYORDERED) AS Q1,
percentile_cont(0.75) WITHIN GROUP (ORDER BY QUANTITYORDERED) AS Q3,
percentile_cont(0.75) WITHIN GROUP (ORDER BY QUANTITYORDERED) - percentile_cont(0.25) WITHIN GROUP (ORDER BY QUANTITYORDERED)
AS IQR 
FROM SALES_DATASET_RFM_PRJ) AS a)
UPDATE SALES_DATASET_RFM_PRJ
SET QUANTITYORDERED = (SELECT AVG(QUANTITYORDERED)FROM SALES_DATASET_RFM_PRJ)
WHERE QUANTITYORDERED IN (SELECT QUANTITYORDERED FROM SALES_DATASET_RFM_PRJ
WHERE QUANTITYORDERED < (SELECT min_value from twt_min_max_value) OR
QUANTITYORDERED < (SELECT max_value from twt_min_max_value))
-- cách 2: z-score
WITH cte AS(
SELECT QUANTITYORDERED,
(SELECT AVG(QUANTITYORDERED) FROM SALES_DATASET_RFM_PRJ)  AS avg, 
(SELECT STDDEV(QUANTITYORDERED) FROM SALES_DATASET_RFM_PRJ) AS stddev
FROM SALES_DATASET_RFM_PRJ),
twt_outliner AS(
SELECT QUANTITYORDERED, (QUANTITYORDERED-avg)/stddev AS z_score
FROM cte
WHERE ABS((QUANTITYORDERED-avg)/stddev) > 2)
UPDATE SALES_DATASET_RFM_PRJ
SET QUANTITYORDERED = SELECT (AVG(QUANTITYORDERED) FROM SALES_DATASET_RFM_PRJ)
WHERE QUANTITYORDERED IN (SELECT QUANTITYORDERED FROM twt_outliner)
-- câu 6
CREATE OR REPLACE VIEW SALES_DATASET_RFM_PRJ_CLEAN AS(
	SELECT * FROM SALES_DATASET_RFM_PRJ)
